# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Map.all.destroy
world = Map.create(
[
  { type: "world", country: "Afghanistan",    code: 4, abbreviation: "AFG", tier: "2" },
  { type: "world", country: "Aland Islands",    code: 248, abbreviation: "ALA", tier: "nil" },
  { type: "world", country: "Albania",    code: 8, abbreviation: "ALB", tier: "2" },
  { type: "world", country: "Algeria",    code: 12, abbreviation: "DZA", tier: "4" },
  { type: "world", country: "American Samoa",    code: 16, abbreviation: "ASM", tier: "nil" },
  { type: "world", country: "Andorra",    code: 20, abbreviation: "AND", tier: "nil" },
  { type: "world", country: "Angola",    code: 24, abbreviation: "AGO", tier: "3" },
  { type: "world", country: "Anguilla",    code: 660, abbreviation: "AIA", tier: "nil" },
  { type: "world", country: "Antarctica",    code: 10, abbreviation: "ATA", tier: "nil" },
  { type: "world", country: "Antigua & Barbuda",    code: 28, abbreviation: "ATG", tier: "3" },
  { type: "world", country: "Argentina",    code: 32, abbreviation: "ARG", tier: "2" },
  { type: "world", country: "Armenia",    code: 51, abbreviation: "ARM", tier: "1" },
  { type: "world", country: "Aruba",    code: 533, abbreviation: "ABW", tier: "2" },
  { type: "world", country: "Australia",    code: 36, abbreviation: "AUS", tier: "1" },
  { type: "world", country: "Austria",    code: 40, abbreviation: "AUT", tier: "1" },
  { type: "world", country: "Azerbaijan",    code: 31, abbreviation: "AZE", tier: "2" },
  { type: "world", country: "Bahamas",    code: 44, abbreviation: "BHS", tier: "2" },
  { type: "world", country: "Bahrain",    code: 48, abbreviation: "BHR", tier: "3" },
  { type: "world", country: "Bangladesh",    code: 50, abbreviation: "BGD", tier: "2" },
  { type: "world", country: "Barbados",    code: 52, abbreviation: "BRB", tier: "2" },
  { type: "world", country: "Belarus",    code: 112, abbreviation: "BLR", tier: "3" },
  { type: "world", country: "Belgium",    code: 56, abbreviation: "BEL", tier: "1" },
  { type: "world", country: "Belize",    code: 84, abbreviation: "BLZ", tier: "3" },
  { type: "world", country: "Benin",    code: 204, abbreviation: "BEN", tier: "2" },
  { type: "world", country: "Bermuda",    code: 60, abbreviation: "BMU", tier: "nil" },
  { type: "world", country: "Bhutan",    code: 64, abbreviation: "BTN", tier: "2" },
  { type: "world", country: "Bolivia, Plurinational State of",    code: 68, abbreviation: "BOL", tier: "3" },
  { type: "world", country: "Bonaire, Sint Eustatius and Saba",    code: 535, abbreviation: "BES", tier: "nil" },
  { type: "world", country: "Bosnia & Herzegovina",    code: 70, abbreviation: "BIH", tier: "3" },
  { type: "world", country: "Botswana",    code: 72, abbreviation: "BWA", tier: "3" },
  { type: "world", country: "Bouvet Island",    code: 74, abbreviation: "BVT", tier: "nil" },
  { type: "world", country: "Brazil",    code: 76, abbreviation: "BRA", tier: "2" },
  { type: "world", country: "British Indian Ocean Territory",    code: 92, abbreviation: "VGB", tier: "nil" },
  { type: "world", country: "Brunei Darussalam",    code: 96, abbreviation: "BRN", tier: "2" },
  { type: "world", country: "Bulgaria",    code: 100, abbreviation: "BGR", tier: "2" },
  { type: "world", country: "Burkina Faso",    code: 854, abbreviation: "BFA", tier: "2" },
  { type: "world", country: "Burundi",    code: 108, abbreviation: "BDI", tier: "3" },
  { type: "world", country: "Cabo Verde",    code: 132, abbreviation: "CPV", tier: "2" },
  { type: "world", country: "Cambodia",    code: 116, abbreviation: "KHM", tier: "3" },
  { type: "world", country: "Cameroon",    code: 120, abbreviation: "CMR", tier: "2" },
  { type: "world", country: "Canada",    code: 124, abbreviation: "CAN", tier: "1" },
  { type: "world", country: "Cayman Islands",    code: 136, abbreviation: "CYM", tier: "nil" },
  { type: "world", country: "Central African Republic",    code: 140, abbreviation: "CAF", tier: "4" },
  { type: "world", country: "Chad",    code: 148, abbreviation: "TCD", tier: "2" },
  { type: "world", country: "Chile",    code: 152, abbreviation: "CHL", tier: "1" },
  { type: "world", country: "China (PRC)",    code: 156, abbreviation: "CHN", tier: "3" },
  { type: "world", country: "Christmas Island",    code: 162, abbreviation: "CXR", tier: "nil" },
  { type: "world", country: "Cocos (Keeling) Islands",    code: 166, abbreviation: "CCK", tier: "nil" },
  { type: "world", country: "Colombia",    code: 170, abbreviation: "COL", tier: "2" },
  { type: "world", country: "Comoros",    code: 174, abbreviation: "COM", tier: "3" },
  { type: "world", country: "Congo",    code: 178, abbreviation: "COG", tier: "2" },
  { type: "world", country: "Congo, the Democratic Republic of the",    code: 180, abbreviation: "COD", tier: "4" },
  { type: "world", country: "Cook Islands",    code: 184, abbreviation: "COK", tier: "nil" },
  { type: "world", country: "Costa Rica",    code: 188, abbreviation: "CRI", tier: "2" },
  { type: "world", country: "Cote d�۪Ivoire",    code: 384, abbreviation: "CIV", tier: "2" },
  { type: "world", country: "Croatia",    code: 191, abbreviation: "HRV", tier: "2" },
  { type: "world", country: "Cuba",    code: 192, abbreviation: "CUB", tier: "4" },
  { type: "world", country: "Cura̤ao",    code: 531, abbreviation: "CUW", tier: "2" },
  { type: "world", country: "Cyprus",    code: 196, abbreviation: "CYP", tier: "3" },
  { type: "world", country: "Czech Republic",    code: 203, abbreviation: "CZE", tier: "1" },
  { type: "world", country: "Denmark",    code: 208, abbreviation: "DNK", tier: "1" },
  { type: "world", country: "Djibouti",    code: 262, abbreviation: "DJI", tier: "3" },
  { type: "world", country: "Dominica",    code: 212, abbreviation: "DMA", tier: "nil" },
  { type: "world", country: "Dominican Republic",    code: 214, abbreviation: "DOM", tier: "2" },
  { type: "world", country: "Ecuador",    code: 218, abbreviation: "ECU", tier: "2" },
  { type: "world", country: "Egypt",    code: 818, abbreviation: "EGY", tier: "2" },
  { type: "world", country: "El Salvador",    code: 222, abbreviation: "SLV", tier: "2" },
  { type: "world", country: "Equatorial Guinea",    code: 226, abbreviation: "GNQ", tier: "4" },
  { type: "world", country: "Eritrea",    code: 232, abbreviation: "ERI", tier: "4" },
  { type: "world", country: "Estonia",    code: 233, abbreviation: "EST", tier: "2" },
  { type: "world", country: "Ethiopia",    code: 231, abbreviation: "ETH", tier: "2" },
  { type: "world", country: "Falkland Islands (Malvinas)",    code: 238, abbreviation: "FLK", tier: "nil" },
  { type: "world", country: "Faroe Islands",    code: 234, abbreviation: "FRO", tier: "nil" },
  { type: "world", country: "Fiji",    code: 242, abbreviation: "FJI", tier: "2" },
  { type: "world", country: "Finland",    code: 246, abbreviation: "FIN", tier: "1" },
  { type: "world", country: "France",    code: 250, abbreviation: "FRA", tier: "1" },
  { type: "world", country: "French Guiana",    code: 254, abbreviation: "GUF", tier: "nil" },
  { type: "world", country: "French Polynesia",    code: 258, abbreviation: "PYF", tier: "nil" },
  { type: "world", country: "French Southern Territories",    code: 260, abbreviation: "ATF", tier: "nil" },
  { type: "world", country: "Gabon",    code: 266, abbreviation: "GAB", tier: "2" },
  { type: "world", country: "Gambia",    code: 270, abbreviation: "GMB", tier: "4" },
  { type: "world", country: "Georgia",    code: 268, abbreviation: "GEO", tier: "2" },
  { type: "world", country: "Germany",    code: 276, abbreviation: "DEU", tier: "1" },
  { type: "world", country: "Ghana",    code: 288, abbreviation: "GHA", tier: "2" },
  { type: "world", country: "Gibraltar",    code: 292, abbreviation: "GIB", tier: "nil" },
  { type: "world", country: "Greece",    code: 300, abbreviation: "GRC", tier: "2" },
  { type: "world", country: "Greenland",    code: 304, abbreviation: "GRL", tier: "nil" },
  { type: "world", country: "Grenada",    code: 308, abbreviation: "GRD", tier: "nil" },
  { type: "world", country: "Guadeloupe",    code: 312, abbreviation: "GLP", tier: "nil" },
  { type: "world", country: "Guam",    code: 316, abbreviation: "GUM", tier: "nil" },
  { type: "world", country: "Guatemala",    code: 320, abbreviation: "GTM", tier: "2" },
  { type: "world", country: "Guernsey",    code: 831, abbreviation: "GGY", tier: "nil" },
  { type: "world", country: "Guinea",    code: 324, abbreviation: "GIN", tier: "3" },
  { type: "world", country: "Guinea-Bissau",    code: 624, abbreviation: "GNB", tier: "4" },
  { type: "world", country: "Guyana",    code: 328, abbreviation: "GUY", tier: "3" },
  { type: "world", country: "Haiti",    code: 332, abbreviation: "HTI", tier: "3" },
  { type: "world", country: "Heard Island and McDonald Islands",    code: 334, abbreviation: "HMD", tier: "nil" },
  { type: "world", country: "Holy See (Vatican City State)",    code: 336, abbreviation: "VAT", tier: "nil" },
  { type: "world", country: "Honduras",    code: 340, abbreviation: "HND", tier: "2" },
  { type: "world", country: "Hong Kong",    code: 44, abbreviation: "HKG", tier: "2" },
  { type: "world", country: "Hungary",    code: 348, abbreviation: "HUN", tier: "2" },
  { type: "world", country: "Iceland",    code: 352, abbreviation: "ISL", tier: "1" },
  { type: "world", country: "India",    code: 356, abbreviation: "IND", tier: "2" },
  { type: "world", country: "Indonesia",    code: 360, abbreviation: "IDN", tier: "2" },
  { type: "world", country: "Iran, Islamic Republic of",    code: 364, abbreviation: "IRN", tier: "4" },
  { type: "world", country: "Iraq",    code: 368, abbreviation: "IRQ", tier: "2" },
  { type: "world", country: "Ireland",    code: 372, abbreviation: "IRL", tier: "1" },
  { type: "world", country: "Isle of Man",    code: 833, abbreviation: "IMN", tier: "nil" },
  { type: "world", country: "Israel",    code: 376, abbreviation: "ISR", tier: "1" },
  { type: "world", country: "Italy",    code: 380, abbreviation: "ITA", tier: "1" },
  { type: "world", country: "Jamaica",    code: 388, abbreviation: "JAM", tier: "3" },
  { type: "world", country: "Japan",    code: 392, abbreviation: "JPN", tier: "2" },
  { type: "world", country: "Jersey",    code: 832, abbreviation: "JEY", tier: "nil" },
  { type: "world", country: "Jordan",    code: 400, abbreviation: "JOR", tier: "2" },
  { type: "world", country: "Kazakhstan",    code: 398, abbreviation: "KAZ", tier: "2" },
  { type: "world", country: "Kenya",    code: 404, abbreviation: "KEN", tier: "3" },
  { type: "world", country: "Kiribati",    code: 296, abbreviation: "KIR", tier: "2" },
  { type: "world", country: "Korea, Democratic People's Republic of",    code: 408, abbreviation: "PRK", tier: "4" },
  { type: "world", country: "Korea, Republic of",    code: 410, abbreviation: "KOR", tier: "1" },
  { type: "world", country: "Kuwait",    code: 414, abbreviation: "KWT", tier: "4" },
  { type: "world", country: "Kyrgyzstan",    code: 417, abbreviation: "KGZ", tier: "2" },
  { type: "world", country: "Lao People's Democratic Republic",    code: 418, abbreviation: "LAO", tier: "3" },
  { type: "world", country: "Latvia",    code: 428, abbreviation: "LVA", tier: "2" },
  { type: "world", country: "Lebanon",    code: 422, abbreviation: "LBN", tier: "3" },
  { type: "world", country: "Lesotho",    code: 426, abbreviation: "LSO", tier: "3" },
  { type: "world", country: "Liberia",    code: 430, abbreviation: "LBR", tier: "2" },
  { type: "world", country: "Libya",    code: 434, abbreviation: "LBY", tier: "4" },
  { type: "world", country: "Liechtenstein",    code: 438, abbreviation: "LIE", tier: "nil" },
  { type: "world", country: "Lithuania",    code: 440, abbreviation: "LTU", tier: "2" },
  { type: "world", country: "Luxembourg",    code: 442, abbreviation: "LUX", tier: "1" },
  { type: "world", country: "Macao",    code: 446, abbreviation: "MAC", tier: "2" },
  { type: "world", country: "Macedonia, the former Yugoslav Republic of",    code: 807, abbreviation: "MKD", tier: "1" },
  { type: "world", country: "Madagascar",    code: 450, abbreviation: "MDG", tier: "3" },
  { type: "world", country: "Malawi",    code: 454, abbreviation: "MWI", tier: "2" },
  { type: "world", country: "Malaysia",    code: 458, abbreviation: "MYS", tier: "4" },
  { type: "world", country: "Maldives",    code: 462, abbreviation: "MDV", tier: "2" },
  { type: "world", country: "Mali",    code: 466, abbreviation: "MLI", tier: "3" },
  { type: "world", country: "Malta",    code: 470, abbreviation: "MLT", tier: "2" },
  { type: "world", country: "Marshall Islands",    code: 584, abbreviation: "MHL", tier: "3" },
  { type: "world", country: "Martinique",    code: 474, abbreviation: "MTQ", tier: "nil" },
  { type: "world", country: "Mauritania",    code: 478, abbreviation: "MRT", tier: "4" },
  { type: "world", country: "Mauritius",    code: 480, abbreviation: "MUS", tier: "2" },
  { type: "world", country: "Mayotte",    code: 175, abbreviation: "MYT", tier: "nil" },
  { type: "world", country: "Mexico",    code: 484, abbreviation: "MEX", tier: "2" },
  { type: "world", country: "Micronesia, Federated States of",    code: 583, abbreviation: "FSM", tier: "2" },
  { type: "world", country: "Moldova, Republic of",    code: 498, abbreviation: "MDA", tier: "2" },
  { type: "world", country: "Monaco",    code: 492, abbreviation: "MCO", tier: "nil" },
  { type: "world", country: "Mongolia",    code: 496, abbreviation: "MNG", tier: "2" },
  { type: "world", country: "Montenegro",    code: 499, abbreviation: "MNE", tier: "2" },
  { type: "world", country: "Montserrat",    code: 500, abbreviation: "MSR", tier: "nil" },
  { type: "world", country: "Morocco",    code: 504, abbreviation: "MAR", tier: "3" },
  { type: "world", country: "Mozambique",    code: 508, abbreviation: "MOZ", tier: "2" },
  { type: "world", country: "Myanmar",    code: 104, abbreviation: "MMR", tier: "nil" },
  { type: "world", country: "Namibia",    code: 516, abbreviation: "NAM", tier: "3" },
  { type: "world", country: "Nauru",    code: 520, abbreviation: "NRU", tier: "nil" },
  { type: "world", country: "Nepal",    code: 524, abbreviation: "NPL", tier: "2" },
  { type: "world", country: "Netherlands",    code: 528, abbreviation: "NLD", tier: "1" },
  { type: "world", country: "New Caledonia",    code: 540, abbreviation: "NCL", tier: "nil" },
  { type: "world", country: "New Zealand",    code: 554, abbreviation: "NZL", tier: "1" },
  { type: "world", country: "Nicaragua",    code: 558, abbreviation: "NIC", tier: "1" },
  { type: "world", country: "Niger",    code: 562, abbreviation: "NER", tier: "2" },
  { type: "world", country: "Nigeria",    code: 566, abbreviation: "NGA", tier: "2" },
  { type: "world", country: "Niue",    code: 570, abbreviation: "NIU", tier: "nil" },
  { type: "world", country: "Norfolk Island",    code: 574, abbreviation: "NFK", tier: "nil" },
  { type: "world", country: "Northern Mariana Islands",    code: 580, abbreviation: "MNP", tier: "nil" },
  { type: "world", country: "Norway",    code: 578, abbreviation: "NOR", tier: "1" },
  { type: "world", country: "Oman",    code: 512, abbreviation: "OMN", tier: "2" },
  { type: "world", country: "Pakistan",    code: 586, abbreviation: "PAK", tier: "3" },
  { type: "world", country: "Palau",    code: 585, abbreviation: "PLW", tier: "2" },
  { type: "world", country: "Palestine, State of",    code: 275, abbreviation: "PSE", tier: "nil" },
  { type: "world", country: "Panama",    code: 591, abbreviation: "PAN", tier: "3" },
  { type: "world", country: "Papua New Guinea",    code: 598, abbreviation: "PNG", tier: "4" },
  { type: "world", country: "Paraguay",    code: 600, abbreviation: "PRY", tier: "2" },
  { type: "world", country: "Peru",    code: 604, abbreviation: "PER", tier: "2" },
  { type: "world", country: "Philippines",    code: 608, abbreviation: "PHL", tier: "2" },
  { type: "world", country: "Pitcairn",    code: 612, abbreviation: "PCN", tier: "nil" },
  { type: "world", country: "Poland",    code: 616, abbreviation: "POL", tier: "1" },
  { type: "world", country: "Portugal",    code: 620, abbreviation: "PRT", tier: "2" },
  { type: "world", country: "Puerto Rico",    code: 630, abbreviation: "PRI", tier: "nil" },
  { type: "world", country: "Qatar",    code: 634, abbreviation: "QAT", tier: "3" },
  { type: "world", country: "R̩union",    code: 638, abbreviation: "REU", tier: "nil" },
  { type: "world", country: "Romania",    code: 642, abbreviation: "ROU", tier: "2" },
  { type: "world", country: "Russian Federation",    code: 643, abbreviation: "RUS", tier: "4" },
  { type: "world", country: "Rwanda",    code: 646, abbreviation: "RWA", tier: "3" },
  { type: "world", country: "Saint Barth̩lemy",    code: 652, abbreviation: "BLM", tier: "nil" },
  { type: "world", country: "Saint Helena, Ascension and Tristan da Cunha",    code: 654, abbreviation: "SHN", tier: "nil" },
  { type: "world", country: "Saint Kitts and Nevis",    code: 659, abbreviation: "KNA", tier: "nil" },
  { type: "world", country: "Saint Lucia",    code: 662, abbreviation: "LCA", tier: "nil" },
  { type: "world", country: "Saint Martin (French part)",    code: 663, abbreviation: "MAF", tier: "nil" },
  { type: "world", country: "Saint Pierre and Miquelon",    code: 666, abbreviation: "SPM", tier: "nil" },
  { type: "world", country: "Saint Vincent and the Grenadines",    code: 670, abbreviation: "VCT", tier: "nil" },
  { type: "world", country: "Samoa",    code: 882, abbreviation: "WSM", tier: "nil" },
  { type: "world", country: "San Marino",    code: 674, abbreviation: "SMR", tier: "nil" },
  { type: "world", country: "Sao Tome and Principe",    code: 678, abbreviation: "STP", tier: "nil" },
  { type: "world", country: "Saudi Arabia",    code: 682, abbreviation: "SAU", tier: "4" },
  { type: "world", country: "Senegal",    code: 686, abbreviation: "SEN", tier: "2" },
  { type: "world", country: "Serbia",    code: 688, abbreviation: "SRB", tier: "2" },
  { type: "world", country: "Seychelles",    code: 690, abbreviation: "SYC", tier: "2" },
  { type: "world", country: "Sierra Leone",    code: 694, abbreviation: "SLE", tier: "2" },
  { type: "world", country: "Singapore",    code: 702, abbreviation: "SGP", tier: "2" },
  { type: "world", country: "Sint Maarten (Dutch part)",    code: 534, abbreviation: "SXM", tier: "nil" },
  { type: "world", country: "Slovakia",    code: 703, abbreviation: "SVK", tier: "1" },
  { type: "world", country: "Slovenia",    code: 705, abbreviation: "SVN", tier: "1" },
  { type: "world", country: "Solomon Islands",    code: 90, abbreviation: "SLB", tier: "3" },
  { type: "world", country: "Somalia",    code: 706, abbreviation: "SOM", tier: "nil" },
  { type: "world", country: "South Africa",    code: 710, abbreviation: "ZAF", tier: "2" },
  { type: "world", country: "South Georgia and the South Sandwich Islands",    code: 239, abbreviation: "SGS", tier: "nil" },
  { type: "world", country: "South Sudan",    code: 728, abbreviation: "SSD", tier: "3" },
  { type: "world", country: "Spain",    code: 724, abbreviation: "ESP", tier: "1" },
  { type: "world", country: "Sri Lanka",    code: 144, abbreviation: "LKA", tier: "3" },
  { type: "world", country: "Sudan",    code: 729, abbreviation: "SDN", tier: "3" },
  { type: "world", country: "Suriname",    code: 740, abbreviation: "SUR", tier: "3" },
  { type: "world", country: "Svalbard and Jan Mayen",    code: 744, abbreviation: "SJM", tier: "nil" },
  { type: "world", country: "Swaziland",    code: 748, abbreviation: "SWZ", tier: "2" },
  { type: "world", country: "Sweden",    code: 752, abbreviation: "SWE", tier: "1" },
  { type: "world", country: "Switzerland",    code: 756, abbreviation: "CHE", tier: "1" },
  { type: "world", country: "Syria",    code: 760, abbreviation: "SYR", tier: "4" },
  { type: "world", country: "Taiwan, Province of China",    code: 158, abbreviation: "TWN", tier: "1" },
  { type: "world", country: "Tajikistan",    code: 762, abbreviation: "TJK", tier: "2" },
  { type: "world", country: "Tanzania, United Republic of",    code: 834, abbreviation: "TZA", tier: "3" },
  { type: "world", country: "Thailand",    code: 764, abbreviation: "THA", tier: "4" },
  { type: "world", country: "Timor-Leste",    code: 626, abbreviation: "TLS", tier: "3" },
  { type: "world", country: "Togo",    code: 768, abbreviation: "TGO", tier: "2" },
  { type: "world", country: "Tokelau",    code: 772, abbreviation: "TKL", tier: "nil" },
  { type: "world", country: "Tonga",    code: 776, abbreviation: "TON", tier: "2" },
  { type: "world", country: "Trinidad & Tobago",    code: 780, abbreviation: "TTO", tier: "2" },
  { type: "world", country: "Tunisia",    code: 788, abbreviation: "TUN", tier: "3" },
  { type: "world", country: "Turkey",    code: 792, abbreviation: "TUR", tier: "2" },
  { type: "world", country: "Turkmenistan",    code: 795, abbreviation: "TKM", tier: "3" },
  { type: "world", country: "TURKS AND CAICOS ISLANDS",    code: 796, abbreviation: "TCA", tier: "nil" },
  { type: "world", country: "TUVALU",    code: 798, abbreviation: "TUV", tier: "nil" },
  { type: "world", country: "Uganda",    code: 800, abbreviation: "UGA", tier: "2" },
  { type: "world", country: "Ukraine",    code: 804, abbreviation: "UKR", tier: "3" },
  { type: "world", country: "United Arab Emirates",    code: 784, abbreviation: "ARE", tier: "2" },
  { type: "world", country: "United Kingdom",    code: 826, abbreviation: "GBR", tier: "1" },
  { type: "world", country: "United States of America",    code: 840, abbreviation: "USA", tier: "1" },
  { type: "world", country: "United States Minor Outlying Islands",    code: 581, abbreviation: "UMI", tier: "nil" },
  { type: "world", country: "Uruguay",    code: 858, abbreviation: "URY", tier: "3" },
  { type: "world", country: "Uzbekistan",    code: 860, abbreviation: "UZB", tier: "4" },
  { type: "world", country: "Vanuatu",    code: 548, abbreviation: "VUT", tier: "nil" },
  { type: "world", country: "Venezuela",    code: 862, abbreviation: "VEN", tier: "4" },
  { type: "world", country: "Vietnam",    code: 704, abbreviation: "VNM", tier: "2" },
  { type: "world", country: "Virgin Islands, British",    code: 92, abbreviation: "VGB", tier: "nil" },
  { type: "world", country: "Virgin Islands, U.S.",    code: 850, abbreviation: "VIR", tier: "nil" },
  { type: "world", country: "Wallis and Futuna",    code: 876, abbreviation: "WLF", tier: "nil" },
  { type: "world", country: "Western Sahara",    code: 732, abbreviation: "ESH", tier: "nil" },
  { type: "world", country: "Yemen",    code: 887, abbreviation: "YEM", tier: "4" },
  { type: "world", country: "Zambia",    code: 894, abbreviation: "ZMB", tier: "2" },
  { type: "world", country: "Zimbabwe",    code: 716, abbreviation: "ZWE", tier: "4"  }
])