# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Statistic.all.destroy
statistic = Statistic.create([
  {id: 1, category: "statistic",     source: "UN.GIFT",    author: "http://www.endcrowd.com",                                                               sentence: "Every 30 seconds, another person becomes a victim of human trafficking."}, 
  {id: 2, category: "statistic",     source: "UN.GIFT",    author: "http://www.endcrowd.com",                                                               sentence: "Most victims of trafficking are between the ages of 18 and 24."}, 
  {id: 3, category: "statistic",     source: "UN.GIFT",    author: "http://www.endcrowd.com",                                                               sentence: "46% of people know their trafficker or recruiter prior to being trafficked."},
  {id: 4, category: "statistic",     source: "Free the Slaves",    author: "http://www.endcrowd.com",                                                       sentence: "The average cost of a modern day slave is a mere $90."},
  {id: 5, category: "statistic",     source: "Polaris",    author: "http://www.endcrowd.com",                                                               sentence: "The average age of entry into prostitution is 12-14 years of age; this includes the United States of America."},
  {id: 6, category: "statistic",     source: "UN.GIFT",    author: "http://www.endcrowd.com",                                                               sentence: "Modern day slavery affects every continent and every type of economy."},
  {id: 7, category: "statistic",     source: "The 2013 Global Slavery Index",    author: "http://www.endcrowd.com",                                         sentence: "Many of this western North African country’s enslaved population are victims of forced marriage."},
  {id: 8, category: "statistic",     source: "Ernie Allen, National Center for Missing and Exploited Children",    author: "http://www.rescuefreedom.org",  sentence: "Between 100,000-300,000 U.S. children are enslaved in sex trafficking each year."},
  {id: 9, category: "statistic",     source: "National Center for Mission & Exploited Children",    author: "http://www.rescuefreedom.org",                 sentence: "Approximately 20% of all Internet pornography involves children who are victims of human trafficking."},
  {id: 10, category: "statistic",    source: "UNODC",    author: "http://www.unodc.org",                                                                    sentence: "Most trafficking is carried out by people whose nationality is the same as that of their victim."},
  {id: 11, category: "statistic",    source: "UNODC",    author: "http://www.unodc.org",                                                                    sentence: "Female offenders have a prominent role in human trafficking; former victims become perpetrators to escape their own victimization."},
  {id: 12, category: "statistic",    source: "Carissa Phelps, founder and CEO of Runaway Girl, FPC, 2013",    author: "http://www.state.gov",               sentence: "Each time victims are stopped by police or treated like criminals, they are pushed closer to their trafficker."},
  {id: 13, category: "statistic",     source: "European Journal of Crime, Criminal Law & Criminal Justice", author: "Meyer, Silke (2006)",                  sentence: "42% of organs are from illegal human trafficking."},
  {id: 14, category: "statistic",     source: "FBI",                                                     author: "http://www.outofdarkness.org/",           sentence: "FBI reports that the average age that a girl is recruited into prostitution or sex trafficking in the U.S. is 11-14 years-old."},
  {id: 15, category: "statistic",     source: "Global Slavery Index",    author: "http://www.globalslaveryindex.org/",                                      sentence: "In 2013, potential modern slavery cases were reported in fifty states of the US."},
  {id: 16, category: "statistic",     source: " International Labor Organization ",    author: "http://www.polarisproject.org/",                            sentence: "In 2005, the International Labor Organization estimated that forced labor generates $32 billion in profits worldwide."},
  {id: 17, category: "statistic",     source: " U.S. Department of Justice",    author: "http://www.hopeforjustice.org",                                    sentence: "In 2012, 1 out of 8 endangered American runaways reported were likely child sex trafficking victims."},
  {id: 18, category: "statistic",     source: " National Center for Missing & Exploited Children",    author: "http://www.hopeforjustice.org",              sentence: "75% of  American child victims engaged in prostitution are under the control of a pimp."},
  {id: 19, category: "statistic",     source: "WHO",    author: "http://www.aljazeera.com/",                                                                sentence: "The W.H.O. estimated in 2007 that organ trafficking accounts for between five and 10 per cent of kidney transplants performed. "},
  {id: 20, category: "statistic",     source: "http://www.aljazeera.com/ ",    author: "http://www.aljazeera.com/ and Debra Budiani,",                      sentence: "Most people are coerced into selling their organs through a combination of misinformation and poverty." },
  {id: 21, category: "statistic",     source: "http://www.aljazeera.com/ ",    author: "http://www.aljazeera.com/ and Debra Budiani,",                      sentence: "People can reportedly earn between $3,000 to $15,000 for selling their organs to middlemen who re-sell them for as much as $200,000." },
  {id: 22, category: "statistic",   source: "2014 Trafficking in Persons Report- State Department",     author: "http://www.state.gov/",                    sentence: "International observers report that extremist rebel groups have kidnapped, recruited, and paid for large numbers of child soldiers."},
  {id: 23, category: "statistic",   source: "2014 Trafficking in Persons Report- State Department",     author: "http://www.state.gov/",                    sentence: "Children in conflict zones are vulnerable to being sold to armed groups, and are often forced to participate in armed conflict."},
  {id: 24, category: "statistic",    source: "Washington Times",     author: "Washington Times",                                                            sentence: "Exploiters traffic children to countries like the UK for blood ritual."},
  {id: 25, category: "statistic",    source: "U.S. Department of States ",       author: "Washington Times",                                                sentence: "Traffickers buy and sell children against their will to use their genitals, heads, and blood for ritual sacrifice."},
  {id: 26, category: "statistic",    source: "U.S. Department of States ",       author: "Washington Times",                                                sentence: "The U.S. Department of States recently reported 9000 children missing in Uganda over the last four years."}
  ])

Quote.all.destroy
quote = Quote.create([
  
  {id: 1, category: "sexual exploitation",       source: "2014 Trafficking in Persons Report- State Department",    author: "http://www.state.gov/", sentence: "United States: When teenager Melissa ran away from home, she was quickly found by a man who promised her help, but was actually a pimp who intended to sexually exploit her. He used psychological manipulation and coercion to hold her in prostitution, and advertised her using online sites. Refusal to do what he said was met by beatings and threats. Despite her fear of being found and killed if she ran, Melissa one day managed to escape from a hotel room where he was keeping her. A patron at another hotel nearby helped her reach the police, who arrested her trafficker."},
  {id: 2, category: "sexual exploitation",       source: "2014 Trafficking in Persons Report- State Department",    author: "http://www.state.gov/", sentence: "When she was only eleven years old, \“Guddi\” was recruited by a woman from her village to work as a domestic servant. When she arrived in the city, however, she was taken to a brothel in the red light district and forced into prostitution. She has been trapped in debt bondage by her trafficker ever since."},
  {id: 3, category: "sexual exploitation",       source: "2014 Trafficking in Persons Report- State Department",    author: "http://www.state.gov/", sentence: "Romania-Europe: Ioana and her boyfriend had been dating for a year when they decided to move to England together. He arranged everything for the move, including housing, and Ioana left her job and family in Romania with excitement for a better life. When she arrived in Manchester, everything changed. Her 'boyfriend' and a friend created a profile for Ioana on an adult website and began advertising her for sex, arranging clients, and taking all of her earnings. She was afraid to try to escape, because he had become violent. Now safe, Ioana speaks out about her experience"},
  {id: 4, category: "sexual exploitation",       source: "2014 Trafficking in Persons Report- State Department",    author: "http://www.state.gov/", sentence: "Pakistan – United Arab Emirates: Mariam and her 16-year-old daughter Fatima were promised jobs at a beauty salon in the United Arab Emirates. On their flight from Pakistan, a friendly man gave Mariam his number just in case she needed any help while there. Mariam and Fatima were picked up at the airport by an woman and acquaintance of the person who paid for their flights and promised them jobs. She took their passports. Then, instead of going to a salon, the mother and daughter were made to engage in prostitution to pay for their plane tickets. Mariam had to see her daughter cry every time a client left her room. When she could, Mariam called the man from her flight and confided in him; he encouraged her to contact the police. They convinced their captor that they needed to go to the market, but instead found a taxi and went to the police. During the investigation, the police uncovered other victims, also lured with promises of jobs in a beauty salon."},
  {id: 6, category: "sexual exploitation",      source: "Equality Now",                                               author: "http://www.equalitynow.org/", sentence: "I was prostituted from 14 till I was 27. I got out because I chose to live. The guy I was with was very violent and I ended up in hospital. I remember the nurse yelled at me for being a prostitute. She sewed me up without anesthesia and I left the hospital. I was paralyzed for 3 days. Those 3 days made me think. I decided to catch a train and leave without knowing where I was going. I was in prostitution on and off for 3 years after that, but that was the beginning of my exit."},
  {id: 7, category: "sexual exploitation",      source: "http://www.globalslaveryindex.org/",                         author: "http://www.globalslaveryindex.org/", sentence: "Account contributed by a US male survivor of commercial sexual exploitation.: \"By the time I was 11 years old I was being sold to men for sex by an older teenage boy from one of the group homes that I had been living in. I was repeatedly beaten if I either refused to work or I did not make enough money for my pimp. The trauma of this victimization that I suffered for many years made it very hard for me to see myself as more than a sexual object for the perverted pleasures of men. It took many difficult years to finally get to a place in my life that I could become a thriving member of society.\" "},
  {id: 8, category: "sexual exploitation",      source: "http://www.globalslaveryindex.org/",                         author: "http://www.globalslaveryindex.org/", sentence: "Suparna was 17 when she was trafficked from her hometown in West Bengal by a person named Raj. She was completing her studies in Grade 9 and thought she was being sent to Delhi to marry Raj, who was 20. She was brought to Delhi by a friendly lady who said she was a friend of Raj’s. When she reached Delhi however, she was sold into forced prostitution in the brothels of Garstin Bastion Road. Raj and his friend Raju continuously tortured her physically when she refused to involve herself in sex work. From there she was sold to ladies who were apparently the brothel managers in Garstin Bastion Road. Even there, she was being beaten up and was forced to entertain customers. A man assisted Suparna to escape, but when she returned to her village she suffered harassment and she and her family were forced to move."},
  {id: 9, category: "forced labor", source: "2014 Trafficking in Persons Report- State Department",    author: "Shakti Vahini, Walk Free partner, India.", sentence: "India: Still a teenager, Aanya dropped out of school with the hope of finding work to help her family. Leaving her home in a region rife with poverty, Aanya arrived in the capital and felt lucky to find work in an upscale neighborhood through a domestic worker placement agency. Rather than a good job, Aanya ended up enslaved in a home, locked in, and abused by her employer. For months she endured violent beatings and isolation. Terrified, she worked without pay, forbidden from interacting with—or even calling anyone she knew. With the help of police and anti-trafficking activists, Aanya escaped, and her case has gone to court. Back home with her family and re-enrolled in school, Aanya is receiving follow-up care."},
  {id: 10, category: "forced labor", source: "2014 Trafficking in Persons Report- State Department",    author: "http://www.state.gov/", sentence: "Peru: Oscar’s cousin worked in a bar in the gold mining region of Peru and told him stories of being paid in chunks of gold. Oscar, 16 at the time, left home in hopes of finding similar work. Upon arrival, the mine owner told him that he had to work 90 days to repay the fee his cousin received for recruiting him, and because the owner controlled the river traffic, there were no options for escape. Oscar then realized he had been sold into slavery. Oscar contracted malaria but was refused medical attention and left to die in a hut; the other workers cared for him and fed him out of their own meager rations. Too weak to work in the mines, he was forced to work in the kitchens. After the 90 days were completed, Oscar packed his bags to leave, but the boss told him he was not free because he was only credited for working 30 days. Oscar was not credited with 90 days’ work until he worked for eight months. Upon his return from the Amazon, Oscar was hospitalized for yellow fever. To repay the doctors, he had to borrow money from his family; Oscar believed the only way to repay that debt was to return to work in the jungle."},
  {id: 11, category: "forced labor", source: "2014 Trafficking in Persons Report- State Department",    author: "http://www.state.gov/", sentence: "Philippines – Saudi Arabia: Marie left her home for a job as a domestic worker in Saudi Arabia—the opportunity for a fair wage and a safe workplace made the sacrifice of leaving her family and her life in the Philippines seem worth it. In reality, Marie spent her time in Saudi Arabia being sold from employer to employer—11 in all. In the last home where she worked, she was beaten severely. After her stay in the hospital, she was sent home to the Philippines. She has never been paid for her months of work."},
  {id: 12, category: "forced labor", source: "2014 Trafficking in Persons Report- State Department",    author: "http://www.state.gov/", sentence: "Burma – Thailand: Trusting his recruiters, Myo believed he was leaving his home in Burma to work in a pineapple factory in Thailand. Yet, when he arrived, he was sold to a boat captain for the equivalent of approximately $430. He was held on the boat for 10 months, forced to work, and beaten regularly. On the rare occasion that the boat docked at port, the officers bribed local police to allow them to keep the fishermen on the boat rather than risking them escaping if they were allowed to set foot on shore. Myo was finally able to escape and sought refuge in a temple. He continues to struggle with deafness, having had his head and ear smashed into a block of ice on the fishing boat."},
  {id: 13, category: "forced labor", source: "2014 Trafficking in Persons Report- State Department",    author: "http://www.state.gov/", sentence: "Philippines – Australia: With dreams of successful boxing careers, Czar and three of his friends fell prey to three Australians who helped them procure temporary sports visas and paid for their travel from the Philippines to Sydney. Upon arriving in Australia, the men were already in debt to their captors, who confiscated their passports and forced them into unpaid domestic labor as “houseboys.” Rather than making their way in the boxing industry, they were forced to live in an uninsulated garage with mere table scraps for meals. After three months, Czar finally entered a boxing match, and won the equivalent of approximately $3,500, but the money was taken by his captor. Shortly thereafter, Czar ran away and escaped. One of his friends also escaped, and went to the police. An investigation was opened into their captors on counts of exploitation and human trafficking."},
  {id: 14, category: "forced labor", source: "2014 Trafficking in Persons Report- State Department",    author: "http://www.state.gov/", sentence: "Mexico – United States: Flor Molina was a hard worker and a good seamstress, working two jobs in Mexico to support her three young children. When her sewing teacher told her about a sewing job in the United States, she thought it was a good opportunity. Once they arrived at the border, the woman who arranged their travel took Flor’s identification documents and clothes, “for safekeeping.” She and her teacher were taken to a sewing factory and immediately began working. Beaten and prohibited from leaving the factory, Flor began her days at 4:00 in the morning; she not only worked as a seamstress, but had to clean the factory after the other workers went home. After 40 days, she was allowed to leave to attend church, where she was able to get help. With the help of a local NGO, Flor was able to break free. Now, she is a leader in a U.S. national survivors’ caucus, and advocates for victims’ rights and supply chain transparency."},
  {id: 15, category: "forced labor", source: "2014 Trafficking in Persons Report- State Department",    author: "http://www.state.gov/", sentence: "India: Ajay was only 15 when he was abducted from a city playground one evening and sold to a rich sugarcane farmer, far from home. Upon waking the next morning—and until he was able to escape about a year later—Ajay endured back-breaking work cleaning livestock pens and processing sugarcane. He was forced to work with little food and less sleep, even after he lost a finger while cutting cane. Escape seemed inconceivable to him and the other children on the farm, until one day his owner sent Ajay to run an errand. Ajay seized the chance to escape and began the long journey home to his family. His family celebrated his return—a year after he was abducted—and while they asked the police to investigate what happened to Ajay, many children continue to be held in forced labor on sugarcane farms and elsewhere."},
  {id: 16, category: "forced labor", source: "2014 Trafficking in Persons Report- State Department",    author: "http://www.state.gov/", sentence: "Vietnam: Needing to support their families, teenagers Dung and Chien dropped out of school and went to work as gold miners. The boys were forced to work underground around the clock, under constant surveillance, and controlled by threats. They were told they would not get paid until they had worked for six months. Racked with untreated malaria and malnourished, Dung and Chien organized an escape attempt with some of the other boys being held in the mines, only to be caught and beaten by the foreman. They were able to finally escape with the help of local villagers, who fed them as they hid from the bosses in the jungle. With the help of a local child support center, the boys are looking forward to being reunited with their families."},
  {id: 17, category: "forced labor",   source: "http://www.globalslaveryindex.org/",                    author: "http://www.globalslaveryindex.org/", sentence: "Sandra, a domestic worker from the Pacific Islands exploited in Australia. \“I came to Australia to work as a domestic worker and the family that brought me here, I know them back in my country. They helped me to make my passport, do my visa and arranged everything for me to come here. And I trusted them because they knew me for more than a year in my country… I started work at 7 o’clock in the morning and ended at 9.30 or 10 o’clock. And I was not paid. Never. I was not allowed to go out… it was almost 3 years I had no medical care. I asked a lady help and she called immigration.\” " },
  {id: 18, category: "organ removal", source: "http://www.telegraph.co.uk/",                             author: "Steven Swinford", sentence: "An unnamed girl was brought to the UK from Somalia with the intention of removing her organs and selling them on to those desperate for a transplant. Child protection charities warned that the case was unlikely to be an isolated incident as traffickers were likely to have smuggled a group of children into the country. The case emerged in a government report which showed that the number of human trafficking victims in the UK has risen by more than 50 per cent last year and reached record levels. A total of 371 children were exploited, with the majority of them being used as slaves or sexually abused. They included 95 children from Vietnam, 67 from Nigeria and 25 from China. Others hailed from Romania and Bangladesh."},
  {id: 19, category: "an alternative form of exploitation",   source: "Washington Times",                                          author: "Rights So Divine by Youngbee Dale", sentence: "In 2008, police arrested a witchdoctor couple and a real estate mogul, Godfrey Kajubi, for trafficking 12 year old Joseph for ritual sacrifice. According to the police, Kajubi promised the witchdoctor couple $4021 in exchange for the heads of four children, which he planned to use for ritual.   Kajubi paid $127 for Joseph’s head, and told the couple that he would pay the rest of the promised amount when the couple brought him three more human heads."}, 
  {id: 20, category: "an alternative form of exploitation",   source: "http://www.warchild.org.uk/",                                author: "War Child Organization", sentence: "Agnes was 10 when she was abducted from her family's vegetable garden by Joseph Kony's notorious Lord's Resistance Army. When Agnes was 11 she was forced to kill another child who had tried to escape: \"they told me if I do not kill that person, they will kill me.\" When Agnes was 12 she was raped by one of the rebel commanders who took her as one of his 'wives'.She managed to escape, aged 13, and fled to an army barracks. A few weeks later, she was reunited with her sister."},
  {id: 21, category: "an alternative form of exploitation",   source: "http://www.globalslaveryindex.org/",                         author: "http://www.globalslaveryindex.org/", sentence: "Shahida, a 13 year old victim of forced marriage in Afghanistan: \"When I was 13, my father arranged my marriage with a 45-year-old man, who promised my family money in exchange for me. I was very unhappy with him, but endured life with him for one year before running back to my home. My father was very angry when I returned. He beat me and yelled at me to return to my husband, but not even his heavy beatings were worse than life with my husband. When I refused to return, my father dug a deep hole in the ground. He forced me into it and began to bury me. I still wonder if he really would have buried me alive if the neighbours hadn’t heard my screaming and stopped him.\" "},
  {id: 22, category: "an alternative form of exploitation",   source: "http://www.globalslaveryindex.org/",                         author: "http://www.globalslaveryindex.org/", sentence: " Account of women and children forced to beg on the streets of Rzeszow, Poland, 2013. \“The women were told to beg together with their children. Each woman had to make between 200 and 800 Zloty (approx. 50-200 Euro) per day. If they did not bring that money back, they were beaten severely. They were begging every day and in different places, regardless of the weather conditions, mainly at churches, cemeteries and shopping malls. Every woman had to beg with a child and the organizers preferred women with disabled children. Some of the children were given medication or were beaten to remain calm.\" "}
   ])



Map.all.destroy
world = Map.create(
[
  { type: "world", country: "Afghanistan",    code: 4, abbreviation: "AFG", tier: "2" },
  { type: "world", country: "Aland Islands",    code: 248, abbreviation: "ALA", tier: "nil" },
  { type: "world", country: "Albania",    code: 8, abbreviation: "ALB", tier: "2" },
  { type: "world", country: "Algeria",    code: 12, abbreviation: "DZA", tier: "4" },
  { type: "world", country: "American Samoa",    code: 16, abbreviation: "ASM", tier: "nil" },
  { type: "world", country: "Andorra",    code: 20, abbreviation: "AND", tier: "nil" },
  { type: "world", country: "Angola",    code: 24, abbreviation: "AGO", tier: "3" },
  { type: "world", country: "Anguilla",    code: 660, abbreviation: "AIA", tier: "nil" },
  { type: "world", country: "Antarctica",    code: 10, abbreviation: "ATA", tier: "nil" },
  { type: "world", country: "Antigua & Barbuda",    code: 28, abbreviation: "ATG", tier: "3" },
  { type: "world", country: "Argentina",    code: 32, abbreviation: "ARG", tier: "2" },
  { type: "world", country: "Armenia",    code: 51, abbreviation: "ARM", tier: "1" },
  { type: "world", country: "Aruba",    code: 533, abbreviation: "ABW", tier: "2" },
  { type: "world", country: "Australia",    code: 36, abbreviation: "AUS", tier: "1" },
  { type: "world", country: "Austria",    code: 40, abbreviation: "AUT", tier: "1" },
  { type: "world", country: "Azerbaijan",    code: 31, abbreviation: "AZE", tier: "2" },
  { type: "world", country: "Bahamas",    code: 44, abbreviation: "BHS", tier: "2" },
  { type: "world", country: "Bahrain",    code: 48, abbreviation: "BHR", tier: "3" },
  { type: "world", country: "Bangladesh",    code: 50, abbreviation: "BGD", tier: "2" },
  { type: "world", country: "Barbados",    code: 52, abbreviation: "BRB", tier: "2" },
  { type: "world", country: "Belarus",    code: 112, abbreviation: "BLR", tier: "3" },
  { type: "world", country: "Belgium",    code: 56, abbreviation: "BEL", tier: "1" },
  { type: "world", country: "Belize",    code: 84, abbreviation: "BLZ", tier: "3" },
  { type: "world", country: "Benin",    code: 204, abbreviation: "BEN", tier: "2" },
  { type: "world", country: "Bermuda",    code: 60, abbreviation: "BMU", tier: "nil" },
  { type: "world", country: "Bhutan",    code: 64, abbreviation: "BTN", tier: "2" },
  { type: "world", country: "Bolivia, Plurinational State of",    code: 68, abbreviation: "BOL", tier: "3" },
  { type: "world", country: "Bonaire, Sint Eustatius and Saba",    code: 535, abbreviation: "BES", tier: "nil" },
  { type: "world", country: "Bosnia & Herzegovina",    code: 70, abbreviation: "BIH", tier: "3" },
  { type: "world", country: "Botswana",    code: 72, abbreviation: "BWA", tier: "3" },
  { type: "world", country: "Bouvet Island",    code: 74, abbreviation: "BVT", tier: "nil" },
  { type: "world", country: "Brazil",    code: 76, abbreviation: "BRA", tier: "2" },
  { type: "world", country: "British Indian Ocean Territory",    code: 92, abbreviation: "VGB", tier: "nil" },
  { type: "world", country: "Brunei Darussalam",    code: 96, abbreviation: "BRN", tier: "2" },
  { type: "world", country: "Bulgaria",    code: 100, abbreviation: "BGR", tier: "2" },
  { type: "world", country: "Burkina Faso",    code: 854, abbreviation: "BFA", tier: "2" },
  { type: "world", country: "Burundi",    code: 108, abbreviation: "BDI", tier: "3" },
  { type: "world", country: "Cabo Verde",    code: 132, abbreviation: "CPV", tier: "2" },
  { type: "world", country: "Cambodia",    code: 116, abbreviation: "KHM", tier: "3" },
  { type: "world", country: "Cameroon",    code: 120, abbreviation: "CMR", tier: "2" },
  { type: "world", country: "Canada",    code: 124, abbreviation: "CAN", tier: "1" },
  { type: "world", country: "Cayman Islands",    code: 136, abbreviation: "CYM", tier: "nil" },
  { type: "world", country: "Central African Republic",    code: 140, abbreviation: "CAF", tier: "4" },
  { type: "world", country: "Chad",    code: 148, abbreviation: "TCD", tier: "2" },
  { type: "world", country: "Chile",    code: 152, abbreviation: "CHL", tier: "1" },
  { type: "world", country: "China (PRC)",    code: 156, abbreviation: "CHN", tier: "3" },
  { type: "world", country: "Christmas Island",    code: 162, abbreviation: "CXR", tier: "nil" },
  { type: "world", country: "Cocos (Keeling) Islands",    code: 166, abbreviation: "CCK", tier: "nil" },
  { type: "world", country: "Colombia",    code: 170, abbreviation: "COL", tier: "2" },
  { type: "world", country: "Comoros",    code: 174, abbreviation: "COM", tier: "3" },
  { type: "world", country: "Congo",    code: 178, abbreviation: "COG", tier: "2" },
  { type: "world", country: "Congo, the Democratic Republic of the",    code: 180, abbreviation: "COD", tier: "4" },
  { type: "world", country: "Cook Islands",    code: 184, abbreviation: "COK", tier: "nil" },
  { type: "world", country: "Costa Rica",    code: 188, abbreviation: "CRI", tier: "2" },
  { type: "world", country: "Cote d�۪Ivoire",    code: 384, abbreviation: "CIV", tier: "2" },
  { type: "world", country: "Croatia",    code: 191, abbreviation: "HRV", tier: "2" },
  { type: "world", country: "Cuba",    code: 192, abbreviation: "CUB", tier: "4" },
  { type: "world", country: "Cura̤ao",    code: 531, abbreviation: "CUW", tier: "2" },
  { type: "world", country: "Cyprus",    code: 196, abbreviation: "CYP", tier: "3" },
  { type: "world", country: "Czech Republic",    code: 203, abbreviation: "CZE", tier: "1" },
  { type: "world", country: "Denmark",    code: 208, abbreviation: "DNK", tier: "1" },
  { type: "world", country: "Djibouti",    code: 262, abbreviation: "DJI", tier: "3" },
  { type: "world", country: "Dominica",    code: 212, abbreviation: "DMA", tier: "nil" },
  { type: "world", country: "Dominican Republic",    code: 214, abbreviation: "DOM", tier: "2" },
  { type: "world", country: "Ecuador",    code: 218, abbreviation: "ECU", tier: "2" },
  { type: "world", country: "Egypt",    code: 818, abbreviation: "EGY", tier: "2" },
  { type: "world", country: "El Salvador",    code: 222, abbreviation: "SLV", tier: "2" },
  { type: "world", country: "Equatorial Guinea",    code: 226, abbreviation: "GNQ", tier: "4" },
  { type: "world", country: "Eritrea",    code: 232, abbreviation: "ERI", tier: "4" },
  { type: "world", country: "Estonia",    code: 233, abbreviation: "EST", tier: "2" },
  { type: "world", country: "Ethiopia",    code: 231, abbreviation: "ETH", tier: "2" },
  { type: "world", country: "Falkland Islands (Malvinas)",    code: 238, abbreviation: "FLK", tier: "nil" },
  { type: "world", country: "Faroe Islands",    code: 234, abbreviation: "FRO", tier: "nil" },
  { type: "world", country: "Fiji",    code: 242, abbreviation: "FJI", tier: "2" },
  { type: "world", country: "Finland",    code: 246, abbreviation: "FIN", tier: "1" },
  { type: "world", country: "France",    code: 250, abbreviation: "FRA", tier: "1" },
  { type: "world", country: "French Guiana",    code: 254, abbreviation: "GUF", tier: "nil" },
  { type: "world", country: "French Polynesia",    code: 258, abbreviation: "PYF", tier: "nil" },
  { type: "world", country: "French Southern Territories",    code: 260, abbreviation: "ATF", tier: "nil" },
  { type: "world", country: "Gabon",    code: 266, abbreviation: "GAB", tier: "2" },
  { type: "world", country: "Gambia",    code: 270, abbreviation: "GMB", tier: "4" },
  { type: "world", country: "Georgia",    code: 268, abbreviation: "GEO", tier: "2" },
  { type: "world", country: "Germany",    code: 276, abbreviation: "DEU", tier: "1" },
  { type: "world", country: "Ghana",    code: 288, abbreviation: "GHA", tier: "2" },
  { type: "world", country: "Gibraltar",    code: 292, abbreviation: "GIB", tier: "nil" },
  { type: "world", country: "Greece",    code: 300, abbreviation: "GRC", tier: "2" },
  { type: "world", country: "Greenland",    code: 304, abbreviation: "GRL", tier: "nil" },
  { type: "world", country: "Grenada",    code: 308, abbreviation: "GRD", tier: "nil" },
  { type: "world", country: "Guadeloupe",    code: 312, abbreviation: "GLP", tier: "nil" },
  { type: "world", country: "Guam",    code: 316, abbreviation: "GUM", tier: "nil" },
  { type: "world", country: "Guatemala",    code: 320, abbreviation: "GTM", tier: "2" },
  { type: "world", country: "Guernsey",    code: 831, abbreviation: "GGY", tier: "nil" },
  { type: "world", country: "Guinea",    code: 324, abbreviation: "GIN", tier: "3" },
  { type: "world", country: "Guinea-Bissau",    code: 624, abbreviation: "GNB", tier: "4" },
  { type: "world", country: "Guyana",    code: 328, abbreviation: "GUY", tier: "3" },
  { type: "world", country: "Haiti",    code: 332, abbreviation: "HTI", tier: "3" },
  { type: "world", country: "Heard Island and McDonald Islands",    code: 334, abbreviation: "HMD", tier: "nil" },
  { type: "world", country: "Holy See (Vatican City State)",    code: 336, abbreviation: "VAT", tier: "nil" },
  { type: "world", country: "Honduras",    code: 340, abbreviation: "HND", tier: "2" },
  { type: "world", country: "Hong Kong",    code: 44, abbreviation: "HKG", tier: "2" },
  { type: "world", country: "Hungary",    code: 348, abbreviation: "HUN", tier: "2" },
  { type: "world", country: "Iceland",    code: 352, abbreviation: "ISL", tier: "1" },
  { type: "world", country: "India",    code: 356, abbreviation: "IND", tier: "2" },
  { type: "world", country: "Indonesia",    code: 360, abbreviation: "IDN", tier: "2" },
  { type: "world", country: "Iran, Islamic Republic of",    code: 364, abbreviation: "IRN", tier: "4" },
  { type: "world", country: "Iraq",    code: 368, abbreviation: "IRQ", tier: "2" },
  { type: "world", country: "Ireland",    code: 372, abbreviation: "IRL", tier: "1" },
  { type: "world", country: "Isle of Man",    code: 833, abbreviation: "IMN", tier: "nil" },
  { type: "world", country: "Israel",    code: 376, abbreviation: "ISR", tier: "1" },
  { type: "world", country: "Italy",    code: 380, abbreviation: "ITA", tier: "1" },
  { type: "world", country: "Jamaica",    code: 388, abbreviation: "JAM", tier: "3" },
  { type: "world", country: "Japan",    code: 392, abbreviation: "JPN", tier: "2" },
  { type: "world", country: "Jersey",    code: 832, abbreviation: "JEY", tier: "nil" },
  { type: "world", country: "Jordan",    code: 400, abbreviation: "JOR", tier: "2" },
  { type: "world", country: "Kazakhstan",    code: 398, abbreviation: "KAZ", tier: "2" },
  { type: "world", country: "Kenya",    code: 404, abbreviation: "KEN", tier: "3" },
  { type: "world", country: "Kiribati",    code: 296, abbreviation: "KIR", tier: "2" },
  { type: "world", country: "Korea, Democratic People's Republic of",    code: 408, abbreviation: "PRK", tier: "4" },
  { type: "world", country: "Korea, Republic of",    code: 410, abbreviation: "KOR", tier: "1" },
  { type: "world", country: "Kuwait",    code: 414, abbreviation: "KWT", tier: "4" },
  { type: "world", country: "Kyrgyzstan",    code: 417, abbreviation: "KGZ", tier: "2" },
  { type: "world", country: "Lao People's Democratic Republic",    code: 418, abbreviation: "LAO", tier: "3" },
  { type: "world", country: "Latvia",    code: 428, abbreviation: "LVA", tier: "2" },
  { type: "world", country: "Lebanon",    code: 422, abbreviation: "LBN", tier: "3" },
  { type: "world", country: "Lesotho",    code: 426, abbreviation: "LSO", tier: "3" },
  { type: "world", country: "Liberia",    code: 430, abbreviation: "LBR", tier: "2" },
  { type: "world", country: "Libya",    code: 434, abbreviation: "LBY", tier: "4" },
  { type: "world", country: "Liechtenstein",    code: 438, abbreviation: "LIE", tier: "nil" },
  { type: "world", country: "Lithuania",    code: 440, abbreviation: "LTU", tier: "2" },
  { type: "world", country: "Luxembourg",    code: 442, abbreviation: "LUX", tier: "1" },
  { type: "world", country: "Macao",    code: 446, abbreviation: "MAC", tier: "2" },
  { type: "world", country: "Macedonia, the former Yugoslav Republic of",    code: 807, abbreviation: "MKD", tier: "1" },
  { type: "world", country: "Madagascar",    code: 450, abbreviation: "MDG", tier: "3" },
  { type: "world", country: "Malawi",    code: 454, abbreviation: "MWI", tier: "2" },
  { type: "world", country: "Malaysia",    code: 458, abbreviation: "MYS", tier: "4" },
  { type: "world", country: "Maldives",    code: 462, abbreviation: "MDV", tier: "2" },
  { type: "world", country: "Mali",    code: 466, abbreviation: "MLI", tier: "3" },
  { type: "world", country: "Malta",    code: 470, abbreviation: "MLT", tier: "2" },
  { type: "world", country: "Marshall Islands",    code: 584, abbreviation: "MHL", tier: "3" },
  { type: "world", country: "Martinique",    code: 474, abbreviation: "MTQ", tier: "nil" },
  { type: "world", country: "Mauritania",    code: 478, abbreviation: "MRT", tier: "4" },
  { type: "world", country: "Mauritius",    code: 480, abbreviation: "MUS", tier: "2" },
  { type: "world", country: "Mayotte",    code: 175, abbreviation: "MYT", tier: "nil" },
  { type: "world", country: "Mexico",    code: 484, abbreviation: "MEX", tier: "2" },
  { type: "world", country: "Micronesia, Federated States of",    code: 583, abbreviation: "FSM", tier: "2" },
  { type: "world", country: "Moldova, Republic of",    code: 498, abbreviation: "MDA", tier: "2" },
  { type: "world", country: "Monaco",    code: 492, abbreviation: "MCO", tier: "nil" },
  { type: "world", country: "Mongolia",    code: 496, abbreviation: "MNG", tier: "2" },
  { type: "world", country: "Montenegro",    code: 499, abbreviation: "MNE", tier: "2" },
  { type: "world", country: "Montserrat",    code: 500, abbreviation: "MSR", tier: "nil" },
  { type: "world", country: "Morocco",    code: 504, abbreviation: "MAR", tier: "3" },
  { type: "world", country: "Mozambique",    code: 508, abbreviation: "MOZ", tier: "2" },
  { type: "world", country: "Myanmar",    code: 104, abbreviation: "MMR", tier: "nil" },
  { type: "world", country: "Namibia",    code: 516, abbreviation: "NAM", tier: "3" },
  { type: "world", country: "Nauru",    code: 520, abbreviation: "NRU", tier: "nil" },
  { type: "world", country: "Nepal",    code: 524, abbreviation: "NPL", tier: "2" },
  { type: "world", country: "Netherlands",    code: 528, abbreviation: "NLD", tier: "1" },
  { type: "world", country: "New Caledonia",    code: 540, abbreviation: "NCL", tier: "nil" },
  { type: "world", country: "New Zealand",    code: 554, abbreviation: "NZL", tier: "1" },
  { type: "world", country: "Nicaragua",    code: 558, abbreviation: "NIC", tier: "1" },
  { type: "world", country: "Niger",    code: 562, abbreviation: "NER", tier: "2" },
  { type: "world", country: "Nigeria",    code: 566, abbreviation: "NGA", tier: "2" },
  { type: "world", country: "Niue",    code: 570, abbreviation: "NIU", tier: "nil" },
  { type: "world", country: "Norfolk Island",    code: 574, abbreviation: "NFK", tier: "nil" },
  { type: "world", country: "Northern Mariana Islands",    code: 580, abbreviation: "MNP", tier: "nil" },
  { type: "world", country: "Norway",    code: 578, abbreviation: "NOR", tier: "1" },
  { type: "world", country: "Oman",    code: 512, abbreviation: "OMN", tier: "2" },
  { type: "world", country: "Pakistan",    code: 586, abbreviation: "PAK", tier: "3" },
  { type: "world", country: "Palau",    code: 585, abbreviation: "PLW", tier: "2" },
  { type: "world", country: "Palestine, State of",    code: 275, abbreviation: "PSE", tier: "nil" },
  { type: "world", country: "Panama",    code: 591, abbreviation: "PAN", tier: "3" },
  { type: "world", country: "Papua New Guinea",    code: 598, abbreviation: "PNG", tier: "4" },
  { type: "world", country: "Paraguay",    code: 600, abbreviation: "PRY", tier: "2" },
  { type: "world", country: "Peru",    code: 604, abbreviation: "PER", tier: "2" },
  { type: "world", country: "Philippines",    code: 608, abbreviation: "PHL", tier: "2" },
  { type: "world", country: "Pitcairn",    code: 612, abbreviation: "PCN", tier: "nil" },
  { type: "world", country: "Poland",    code: 616, abbreviation: "POL", tier: "1" },
  { type: "world", country: "Portugal",    code: 620, abbreviation: "PRT", tier: "2" },
  { type: "world", country: "Puerto Rico",    code: 630, abbreviation: "PRI", tier: "nil" },
  { type: "world", country: "Qatar",    code: 634, abbreviation: "QAT", tier: "3" },
  { type: "world", country: "R̩union",    code: 638, abbreviation: "REU", tier: "nil" },
  { type: "world", country: "Romania",    code: 642, abbreviation: "ROU", tier: "2" },
  { type: "world", country: "Russian Federation",    code: 643, abbreviation: "RUS", tier: "4" },
  { type: "world", country: "Rwanda",    code: 646, abbreviation: "RWA", tier: "3" },
  { type: "world", country: "Saint Barth̩lemy",    code: 652, abbreviation: "BLM", tier: "nil" },
  { type: "world", country: "Saint Helena, Ascension and Tristan da Cunha",    code: 654, abbreviation: "SHN", tier: "nil" },
  { type: "world", country: "Saint Kitts and Nevis",    code: 659, abbreviation: "KNA", tier: "nil" },
  { type: "world", country: "Saint Lucia",    code: 662, abbreviation: "LCA", tier: "nil" },
  { type: "world", country: "Saint Martin (French part)",    code: 663, abbreviation: "MAF", tier: "nil" },
  { type: "world", country: "Saint Pierre and Miquelon",    code: 666, abbreviation: "SPM", tier: "nil" },
  { type: "world", country: "Saint Vincent and the Grenadines",    code: 670, abbreviation: "VCT", tier: "nil" },
  { type: "world", country: "Samoa",    code: 882, abbreviation: "WSM", tier: "nil" },
  { type: "world", country: "San Marino",    code: 674, abbreviation: "SMR", tier: "nil" },
  { type: "world", country: "Sao Tome and Principe",    code: 678, abbreviation: "STP", tier: "nil" },
  { type: "world", country: "Saudi Arabia",    code: 682, abbreviation: "SAU", tier: "4" },
  { type: "world", country: "Senegal",    code: 686, abbreviation: "SEN", tier: "2" },
  { type: "world", country: "Serbia",    code: 688, abbreviation: "SRB", tier: "2" },
  { type: "world", country: "Seychelles",    code: 690, abbreviation: "SYC", tier: "2" },
  { type: "world", country: "Sierra Leone",    code: 694, abbreviation: "SLE", tier: "2" },
  { type: "world", country: "Singapore",    code: 702, abbreviation: "SGP", tier: "2" },
  { type: "world", country: "Sint Maarten (Dutch part)",    code: 534, abbreviation: "SXM", tier: "nil" },
  { type: "world", country: "Slovakia",    code: 703, abbreviation: "SVK", tier: "1" },
  { type: "world", country: "Slovenia",    code: 705, abbreviation: "SVN", tier: "1" },
  { type: "world", country: "Solomon Islands",    code: 90, abbreviation: "SLB", tier: "3" },
  { type: "world", country: "Somalia",    code: 706, abbreviation: "SOM", tier: "nil" },
  { type: "world", country: "South Africa",    code: 710, abbreviation: "ZAF", tier: "2" },
  { type: "world", country: "South Georgia and the South Sandwich Islands",    code: 239, abbreviation: "SGS", tier: "nil" },
  { type: "world", country: "South Sudan",    code: 728, abbreviation: "SSD", tier: "3" },
  { type: "world", country: "Spain",    code: 724, abbreviation: "ESP", tier: "1" },
  { type: "world", country: "Sri Lanka",    code: 144, abbreviation: "LKA", tier: "3" },
  { type: "world", country: "Sudan",    code: 729, abbreviation: "SDN", tier: "3" },
  { type: "world", country: "Suriname",    code: 740, abbreviation: "SUR", tier: "3" },
  { type: "world", country: "Svalbard and Jan Mayen",    code: 744, abbreviation: "SJM", tier: "nil" },
  { type: "world", country: "Swaziland",    code: 748, abbreviation: "SWZ", tier: "2" },
  { type: "world", country: "Sweden",    code: 752, abbreviation: "SWE", tier: "1" },
  { type: "world", country: "Switzerland",    code: 756, abbreviation: "CHE", tier: "1" },
  { type: "world", country: "Syria",    code: 760, abbreviation: "SYR", tier: "4" },
  { type: "world", country: "Taiwan, Province of China",    code: 158, abbreviation: "TWN", tier: "1" },
  { type: "world", country: "Tajikistan",    code: 762, abbreviation: "TJK", tier: "2" },
  { type: "world", country: "Tanzania, United Republic of",    code: 834, abbreviation: "TZA", tier: "3" },
  { type: "world", country: "Thailand",    code: 764, abbreviation: "THA", tier: "4" },
  { type: "world", country: "Timor-Leste",    code: 626, abbreviation: "TLS", tier: "3" },
  { type: "world", country: "Togo",    code: 768, abbreviation: "TGO", tier: "2" },
  { type: "world", country: "Tokelau",    code: 772, abbreviation: "TKL", tier: "nil" },
  { type: "world", country: "Tonga",    code: 776, abbreviation: "TON", tier: "2" },
  { type: "world", country: "Trinidad & Tobago",    code: 780, abbreviation: "TTO", tier: "2" },
  { type: "world", country: "Tunisia",    code: 788, abbreviation: "TUN", tier: "3" },
  { type: "world", country: "Turkey",    code: 792, abbreviation: "TUR", tier: "2" },
  { type: "world", country: "Turkmenistan",    code: 795, abbreviation: "TKM", tier: "3" },
  { type: "world", country: "TURKS AND CAICOS ISLANDS",    code: 796, abbreviation: "TCA", tier: "nil" },
  { type: "world", country: "TUVALU",    code: 798, abbreviation: "TUV", tier: "nil" },
  { type: "world", country: "Uganda",    code: 800, abbreviation: "UGA", tier: "2" },
  { type: "world", country: "Ukraine",    code: 804, abbreviation: "UKR", tier: "3" },
  { type: "world", country: "United Arab Emirates",    code: 784, abbreviation: "ARE", tier: "2" },
  { type: "world", country: "United Kingdom",    code: 826, abbreviation: "GBR", tier: "1" },
  { type: "world", country: "United States of America",    code: 840, abbreviation: "USA", tier: "1" },
  { type: "world", country: "United States Minor Outlying Islands",    code: 581, abbreviation: "UMI", tier: "nil" },
  { type: "world", country: "Uruguay",    code: 858, abbreviation: "URY", tier: "3" },
  { type: "world", country: "Uzbekistan",    code: 860, abbreviation: "UZB", tier: "4" },
  { type: "world", country: "Vanuatu",    code: 548, abbreviation: "VUT", tier: "nil" },
  { type: "world", country: "Venezuela",    code: 862, abbreviation: "VEN", tier: "4" },
  { type: "world", country: "Vietnam",    code: 704, abbreviation: "VNM", tier: "2" },
  { type: "world", country: "Virgin Islands, British",    code: 92, abbreviation: "VGB", tier: "nil" },
  { type: "world", country: "Virgin Islands, U.S.",    code: 850, abbreviation: "VIR", tier: "nil" },
  { type: "world", country: "Wallis and Futuna",    code: 876, abbreviation: "WLF", tier: "nil" },
  { type: "world", country: "Western Sahara",    code: 732, abbreviation: "ESH", tier: "nil" },
  { type: "world", country: "Yemen",    code: 887, abbreviation: "YEM", tier: "4" },
  { type: "world", country: "Zambia",    code: 894, abbreviation: "ZMB", tier: "2" },
  { type: "world", country: "Zimbabwe",    code: 716, abbreviation: "ZWE", tier: "4"  }
])